name: Lint

on: workflow_call

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Formatters
        run: pip install black flake8

      - name: Run Formatters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          black_args: "--exclude='.*_pb2.py'"
          auto_fix: true
          git_name: "linter-bot"
          git_email: "linter-bot@skootride.com"

      - name: Run Linters
        uses: wearerequired/lint-action@v1
        with:
          flake8: true
          flake8_args: "--max-line-length=88 --select=C,E,F,W,B,B950 --extend-ignore=E203,E501 --max-complexity=18 --exclude='*_pb2.py'"
          git_name: "linter-bot"
          git_email: "linter-bot@skootride.com"
